server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 400
    min-spare-threads: 20
baseUrl: walkboot
spring:
  application:
    name: walk-boot-app
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://123.56.216.33:3306/walkboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: walk
    password: 2019Walk.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  # 数据库连接池配置
  druid:
    initial-size: 3 #初始化连接池大小
    max-active: 50 #最大连接数
    min-idle: 1
    max-wait: 6000
    validation-query: select 'x'
    validationQueryTimeout: 5
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    stat-view-servlet:
      # 默认true 内置监控页面首页/druid/index.html
      enabled: true
      url-pattern: /druid/*
      # 允许清空统计数据
      reset-enable: true
      login-username: root
      login-password: ENC(F4B0s6u9xcDw3V+P0qC4CA==)
      # IP白名单 多个逗号分隔
      allow:
      # IP黑名单
      deny:
  redis:
    host: 127.0.0.1
    password: 123456
    # 数据库索引 默认0
    database: 0
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S
  jackson:
    time-zone: GMT+8

# 日志配置
logging:
  # 输出级别
  level:
    root: info
  # 指定路径
  path: logs
  file:
    # 最大保存天数
    max-history: 7
    # 每个文件最大大小
    max-size: 10MB

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

